// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"advanced/internal/app"
	"advanced/internal/event"
	"advanced/internal/handler"
	"advanced/internal/handler/demo"
	"advanced/internal/repository/cache"
	"advanced/internal/repository/db"
	"advanced/internal/router"
	"advanced/internal/service/svc"
	"advanced/pkg/token"
	"advanced/pkg/xconfig"
	"advanced/pkg/xdb"
	"advanced/pkg/xlog"
	"advanced/pkg/xredis"
	"advanced/pkg/xserver"
	"advanced/pkg/xserver/http"
)

// Injectors from wire.go:

// 依赖注入构造 Web 应用声明函数
func WireApp(env string) (*xserver.Server, error) {
	conf := xconfig.New(env)
	v := xlog.New(conf)
	v2, err := xdb.New(conf)
	if err != nil {
		return nil, err
	}
	client, err := xredis.New(conf, v)
	if err != nil {
		return nil, err
	}
	pub := event.NewPub(conf, v)
	jwt, err := token.NewJwt(conf, client)
	if err != nil {
		return nil, err
	}
	conn := db.NewConn(v2)
	ctx := &svc.Ctx{
		Conf:     conf,
		Conn:     conn,
		RedisCli: client,
		Logger:   v,
	}
	demoDb := db.NewDemoDb(conn)
	demoCache := cache.NewDemoCache(client)
	demoCtx := &svc.DemoCtx{
		Ctx:       ctx,
		DemoDb:    demoDb,
		DemoCache: demoCache,
		MsgPub:    pub,
		Jwt:       jwt,
	}
	demoSvc := svc.NewDemoSvc(demoCtx)
	demoHandler := &demo.DemoHandler{
		DemoSvc: demoSvc,
	}
	handlerCtx := &handler.Ctx{
		DemoHandler: demoHandler,
	}
	v3 := router.WireServerSet()
	assembly, err := app.NewHttp(conf, v, v2, client, pub, jwt, handlerCtx, v3)
	if err != nil {
		return nil, err
	}
	engine := assembly.Engine
	closer := assembly.Closer
	xserverEngine, err := http.New(conf, v, engine, closer)
	if err != nil {
		return nil, err
	}
	server := xserver.New(xserverEngine)
	return server, nil
}
