// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"advanced/internal/app"
	"advanced/internal/repository/db"
	"advanced/internal/service"
	"advanced/internal/service/svc"
	"advanced/pkg/xconfig"
	"advanced/pkg/xdb"
	"advanced/pkg/xlog"
	"advanced/pkg/xredis"
	"advanced/pkg/xserver"
	"advanced/pkg/xserver/broker"
)

// Injectors from wire.go:

func WireApp(env string) (*xserver.Server, error) {
	conf := xconfig.New(env)
	v := xlog.New(conf)
	v2, err := xdb.New(conf)
	if err != nil {
		return nil, err
	}
	client, err := xredis.New(conf, v)
	if err != nil {
		return nil, err
	}
	engine := app.NewBrokerHealth(conf, v)
	conn := db.NewConn(v2)
	ctx := &svc.Ctx{
		Conf:     conf,
		Conn:     conn,
		RedisCli: client,
		Logger:   v,
	}
	brokerCtx := &svc.BrokerCtx{
		Ctx: ctx,
	}
	brokerSvc := svc.NewBrokerSvc(brokerCtx)
	task := service.TaskSet(brokerSvc)
	v3 := app.NewBrokerChildRun(conf, task)
	xserverEngine, err := broker.New(conf, v, v2, client, engine, v3)
	if err != nil {
		return nil, err
	}
	server := xserver.New(xserverEngine)
	return server, nil
}
