// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"advanced/internal/repository/db"
	"advanced/internal/service"
	"advanced/internal/service/svc"
	"advanced/pkg/xconfig"
	"advanced/pkg/xdb"
	"advanced/pkg/xlog"
	"advanced/pkg/xredis"
	"advanced/pkg/xserver"
	"advanced/pkg/xserver/broker"
)

// Injectors from wire.go:

func WireApp(env string) (*xserver.Server, error) {
	conf := xconfig.New(env)
	logger := xlog.New(conf)
	gormDB, err := xdb.New(conf)
	if err != nil {
		return nil, err
	}
	client, err := xredis.New(conf)
	if err != nil {
		return nil, err
	}
	conn := db.NewConn(gormDB)
	ctx := &svc.Ctx{
		Conf:     conf,
		Conn:     conn,
		RedisCli: client,
	}
	brokerCtx := &svc.BrokerCtx{
		Ctx: ctx,
	}
	brokerSvc := svc.NewBrokerSvc(brokerCtx)
	task := service.TaskSet(brokerSvc)
	engine, err := broker.New(conf, logger, gormDB, client, task)
	if err != nil {
		return nil, err
	}
	server := xserver.New(engine)
	return server, nil
}
