// Code generated by SqlGen. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"gorm.io/gorm"
)

var _ demoDb = (*defaultDemoDb)(nil)

const TableDemo = "demo"

// DemoFields 表 demo 的字段白名单,供 HandleRank 校验可排序字段。
const DemoFields = "id,name,test1,test2,test3,test4,test5,test6,test7,test8,deleted_at,test_a888,test_b"

type (
	demoDb interface {
		Insert(ctx context.Context, data *Demo) (int64, error)
		BatchInsert(ctx context.Context, list []*Demo) ([]int64, error)

		Find(ctx context.Context, id int64) (*Demo, error)
		FindByIds(ctx context.Context, ids []int64) ([]*Demo, error)
		FindFields(ctx context.Context, id int64, fields ...string) (*Demo, error)
		Exist(ctx context.Context, id int64) (bool, error)

		Update(ctx context.Context, newData *Demo, field []string) (int64, error)
		UpdateFields(ctx context.Context, id int64, newData map[string]any) (int64, error)

		SoftDelete(ctx context.Context, ids []int64) error
		Delete(ctx context.Context, ids []int64) error

		Count(ctx context.Context) (int64, error)
	}

	defaultDemoDb struct {
		*Conn
		model *Demo
	}

	// Demo mapped from table <demo>
	Demo struct {
		Id        int64          `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`         //
		Name      string         `gorm:"column:name;type:varchar(45);not null;uniqueIndex:a,priority:1" json:"name"`  // 名称
		Test1     float64        `gorm:"column:test1;type:decimal(10,2) unsigned;not null;default:0.00" json:"test1"` // 测试1
		Test2     int64          `gorm:"column:test2;type:smallint unsigned;not null" json:"test2"`                   // 测试2
		Test3     int64          `gorm:"column:test3;type:year;not null" json:"test3"`                                // 测试3
		Test4     int32          `gorm:"column:test4;type:tinyint unsigned;not null" json:"test4"`                    // 测试4
		Test5     *string        `gorm:"column:test5;type:varchar(255)" json:"test5"`                                 // 测试5
		Test6     string         `gorm:"column:test6;type:varchar(255);not null;default:test6666" json:"test6"`       // 测试6
		Test7     *time.Time     `gorm:"column:test7;type:timestamp" json:"test7"`                                    // 测试7
		Test8     *string        `gorm:"column:test8;type:json" json:"test8"`                                         // 测试8
		DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deletedAt"`                           // 删除时间
		TestA888  *string        `gorm:"column:test_a888;type:varchar(255)" json:"testA888"`                          //
		TestB     int64          `gorm:"column:test_b;type:bigint unsigned;not null" json:"testB"`                    // 测试b
	}
)

func (*Demo) TableName() string {
	return TableDemo
}

func newDemoDb(c *Conn) *defaultDemoDb {
	return &defaultDemoDb{
		Conn:  c,
		model: &Demo{},
	}
}

func (d *defaultDemoDb) Insert(ctx context.Context, data *Demo) (int64, error) {
	var zero int64
	data.Id = zero // 自增主键:清零让 DB 分配;非自增主键保留调用方传入值
	err := d.WithContext(ctx).Create(data).Error
	if err != nil {
		return zero, err
	}
	return data.Id, nil
}

func (d *defaultDemoDb) BatchInsert(ctx context.Context, list []*Demo) ([]int64, error) {
	// 清零主键,避免调用方误传非零 Id 导致插入指定 Id 或主键冲突;非自增主键保留调用方传入值
	for _, v := range list {
		v.Id = *new(int64)
	}
	err := d.WithContext(ctx).Create(list).Error
	if err != nil {
		return nil, err
	}
	ids := make([]int64, len(list))
	for i, v := range list {
		ids[i] = v.Id
	}
	return ids, nil
}

func (d *defaultDemoDb) Find(ctx context.Context, id int64) (*Demo, error) {
	result := &Demo{}
	err := d.WithContext(ctx).First(result, id).Error
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (d *defaultDemoDb) FindFields(ctx context.Context, id int64, fields ...string) (*Demo, error) {
	result := &Demo{}
	query := d.WithContext(ctx)
	// 空 fields 时执行全字段查询,避免 Select([]) 生成无列 SELECT
	if len(fields) > 0 {
		query = query.Select(fields)
	}
	err := query.First(result, id).Error
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (d *defaultDemoDb) FindByIds(ctx context.Context, ids []int64) ([]*Demo, error) {
	var result []*Demo
	err := d.WithContext(ctx).Where("`id` IN (?)", ids).Find(&result).Error
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (d *defaultDemoDb) Exist(ctx context.Context, id int64) (bool, error) {
	var count int64
	err := d.WithContext(ctx).Model(d.model).Where("`id` = ?", id).Limit(1).Count(&count).Error
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

func (d *defaultDemoDb) Update(ctx context.Context, newData *Demo, field []string) (int64, error) {
	engine := d.WithContext(ctx).Model(d.model)
	if len(field) > 0 {
		engine = engine.Select(field)
	}
	result := engine.Omit("id").Where(" `id` = ? ", newData.Id).Updates(newData)
	return result.RowsAffected, result.Error
}

func (d *defaultDemoDb) UpdateFields(ctx context.Context, id int64, newData map[string]any) (int64, error) {
	result := d.WithContext(ctx).Model(d.model).Where(" `id` = ? ", id).Updates(newData)
	return result.RowsAffected, result.Error
}

func (d *defaultDemoDb) SoftDelete(ctx context.Context, ids []int64) error {
	err := d.WithContext(ctx).Where(" `id`  IN (?)  ", ids).Delete(d.model).Error
	return err
}

func (d *defaultDemoDb) Delete(ctx context.Context, ids []int64) error {
	err := d.WithContext(ctx).Where(" `id`  IN (?)  ", ids).Unscoped().Delete(d.model).Error
	return err
}

func (d *defaultDemoDb) Count(ctx context.Context) (int64, error) {
	var count int64
	err := d.WithContext(ctx).Model(d.model).Count(&count).Error
	return count, err
}
