/**
 * @Author: spruce
 * @Date: 2024-03-28 16:29
 * @Desc: sql gen Model 模板
 */

package sqlgen

const NotEditMark = `
// Code generated by SqlGen. DO NOT EDIT.
`

const Header = `
package {{.PackageName}}

import (
	"context"
	"time"

	"gorm.io/gorm"
)

`

const BaseRepoMethod = NotEditMark + Header + `

var  _ {{.InterfaceName}}Repo = (*default{{.StructName}})(nil)

const TableName{{.StructName}} = "{{.TableName}}"

type (
	{{.InterfaceName}}Repo interface {
		Insert(ctx context.Context,data *{{.StructName}}) ({{.PrimaryKeyType}}, error)
		BatchInsert(ctx context.Context,list []*{{.StructName}}) ([]{{.PrimaryKeyType}}, error)

		FindOne(ctx context.Context, id {{.PrimaryKeyType}}) (*{{.StructName}}, error)

		Update(ctx context.Context, newData *{{.StructName}}, column []string)  (int64, error)
		UpdateColumns(ctx context.Context, id {{.PrimaryKeyType}}, newData map[string]any)  (int64, error)

		SoftDelete(ctx context.Context,ids []{{.PrimaryKeyType}}) error
		Delete(ctx context.Context,ids []{{.PrimaryKeyType}}) error

	}

	// {{.StructName}} {{.StructComment}}
	{{.StructName}} struct {
		{{range .Fields}}
            {{.Name}} {{.Type}} ` + "`{{.Tags}}` {{.CommentTag}}" +
	`{{end}}
    }

	default{{.StructName}} struct {
		*Conn
		repo *{{.StructName}}
	}
)


func (*{{.StructName}}) TableName() string {
	return TableName{{.StructName}}
}

func new{{.StructName}}Repo(c *Conn) *default{{.StructName}} {
	return &default{{.StructName}}{
		Conn:   c,
		repo:    &{{.StructName}}{},
	}
}

func (d *default{{.StructName}}) Insert(ctx context.Context,data *{{.StructName}}) ({{.PrimaryKeyType}}, error) {
    data.Id = 0
	err := d.WithContext(ctx).Create(data).Error
	if err != nil {
		return 0,err
	}
	return data.Id,nil
}

func (d *default{{.StructName}}) BatchInsert(ctx context.Context,list []*{{.StructName}}) ([]{{.PrimaryKeyType}}, error) {
	err := d.WithContext(ctx).Create(list).Error
	if err != nil {
		return nil,err
	}
    ids := make([]{{.PrimaryKeyType}}, len(list))
	for i, v := range list {
		ids[i] = v.Id
	}
	return ids,nil
}


func (d *default{{.StructName}}) FindOne(ctx context.Context,id {{.PrimaryKeyType}}) (*{{.StructName}}, error) {
    result:= &{{.StructName}}{}
	err := d.WithContext(ctx).Where(" id = ? ", id).First(result).Error
    if  err != nil {
		return nil, err
	}
	return result, nil
}

func (d *default{{.StructName}}) Update(ctx context.Context,newData *{{.StructName}}, column []string)  (int64, error)  {
	engine := d.WithContext(ctx).Model(d.repo)
	if len(column) > 0 {
		engine = engine.Select(column)
	}
	result := engine.Omit("id").Where(" id = ? ", newData.Id).Updates(newData)
	return result.RowsAffected, result.Error
}

func (d *default{{.StructName}}) UpdateColumns(ctx context.Context,id {{.PrimaryKeyType}}, newData map[string]any)  (int64, error)  {
	result := d.WithContext(ctx).Model(d.repo).Where(" id = ? ", id).Updates(newData)
	return result.RowsAffected, result.Error
}


func (d *default{{.StructName}}) SoftDelete(ctx context.Context,ids []{{.PrimaryKeyType}}) error {
	err :=  d.WithContext(ctx).Where(" id  IN (?)  ", ids).Delete(d.repo).Error
	return err
}

func (d *default{{.StructName}}) Delete(ctx context.Context, ids []{{.PrimaryKeyType}}) error {
	err := d.WithContext(ctx).Where(" id  IN (?)  ", ids).Unscoped().Delete(d.repo).Error
	return err
}

`

const InterfaceMethod = `
package {{.PackageName}}

import (
	"context"
)

//go:generate mockgen -source=./{{.InterfaceName}}.go -destination=../../test/mocks/repository/mysql/{{.InterfaceName}}.go  -package mock_repo_mysql -aux_files mysql=./{{.InterfaceName}}_gen.go

var _ {{.StructName}}Repo = (*custom{{.StructName}})(nil)

type (
	{{.StructName}}Repo interface {
		{{.InterfaceName}}Repo
	}


	custom{{.StructName}} struct {
		*default{{.StructName}}
	}
)

func New{{.StructName}}Repo(c *Conn) {{.StructName}}Repo {
	return &custom{{.StructName}}{
		default{{.StructName}}: new{{.StructName}}Repo(c),
	}
}


`
