// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"basic/internal/controller"
	"basic/internal/repository/cache"
	"basic/internal/repository/db"
	"basic/internal/router"
	"basic/internal/service/svc"
	"basic/pkg/xconfig"
	"basic/pkg/xdb"
	"basic/pkg/xlog"
	"basic/pkg/xredis"
	"basic/pkg/xserver"
	"basic/pkg/xserver/http"
)

// Injectors from wire.go:

// 依赖注入构造 Web 应用声明函数
func WireApp(env string) (*xserver.Server, error) {
	conf := xconfig.New(env)
	logger := xlog.New(conf)
	gormDB, err := xdb.New(conf)
	if err != nil {
		return nil, err
	}
	client, err := xredis.New(conf)
	if err != nil {
		return nil, err
	}
	conn := db.NewConn(gormDB)
	ctx := &svc.Ctx{
		Conf:     conf,
		Conn:     conn,
		RedisCli: client,
		Logger:   logger,
	}
	demoDb := db.NewDemoDb(conn)
	demoCache := cache.NewDemoCache(client)
	demoCtx := &svc.DemoCtx{
		Ctx:       ctx,
		DemoDb:    demoDb,
		DemoCache: demoCache,
	}
	demoSvc := svc.NewDemoSvc(demoCtx)
	demoCtrl := &controller.DemoCtrl{
		DemoSvc: demoSvc,
	}
	serverCtrlCtx := &controller.ServerCtrlCtx{
		DemoCtrl: demoCtrl,
	}
	v := router.WireServerSet()
	engine, err := http.New(conf, logger, gormDB, client, serverCtrlCtx, v)
	if err != nil {
		return nil, err
	}
	server := xserver.New(engine)
	return server, nil
}
